Fix script output

diff --git a/mkosi.images/base/mkosi.extra/usr/local/bin/enter-rw b/mkosi.images/base/mkosi.extra/usr/local/bin/enter-rw
--- a/mkosi.images/base/mkosi.extra/usr/local/bin/enter-rw
+++ b/mkosi.images/base/mkosi.extra/usr/local/bin/enter-rw
@@ -22,8 +22,8 @@ if systemd-confext refresh --noexec=no --mutable=ephemeral && systemd-sysext ref
     if tmpify /var/lib/apt && tmpify /var/lib/dpkg; then
         :
     else
-        printf '%s\n' 'Error: Failed to tmpify /var/lib/apt or /var/lib/dpkg.'
+        printf '%s\n' 'Error: Failed to tmpify /var/lib/apt or /var/lib/dpkg.' >&2
     fi
 else
-    printf '%s\n' 'Error: Failed to refresh systemd-confext or systemd-sysext.'
+    printf '%s\n' 'Error: Failed to refresh systemd-confext or systemd-sysext.' >&2
 fi
